"""Versioned D&O knowledge base (ADR-017)."""

from functools import lru_cache
from pathlib import Path

from app.domain.entities import KnowledgeBase

KNOWLEDGE_BASE_FILE = Path(__file__).with_name("knowledge_base.json")


class JsonConceptCatalog:
    """Loads the catalog generated by scripts/build_knowledge_base.py."""

    def __init__(self, path: Path = KNOWLEDGE_BASE_FILE) -> None:
        self._path = path

    def load(self) -> KnowledgeBase:
        return _load(self._path)


@lru_cache(maxsize=4)
def _load(path: Path) -> KnowledgeBase:
    return KnowledgeBase.model_validate_json(path.read_text(encoding="utf-8"))


__all__ = ["JsonConceptCatalog", "KNOWLEDGE_BASE_FILE"]
